import = ["~/.config/alacritty/rose-pine.toml"]

[font]
builtin_box_drawing = true
size = 14

[font.bold_italic]
family = "IosevkaFireTerm Nerd Font Mono"

[font.bold]
family = "IosevkaFireTerm Nerd Font Mono"

[font.italic]
family = "IosevkaFireTerm Nerd Font Mono"

[font.normal]
family = "IosevkaFireTerm Nerd Font Mono"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "~/.local/share/mise/shims/zellij"]

[window]
startup_mode = "Maximized"
option_as_alt = "Both"
