import = ["~/.config/alacritty/rose-pine.toml"]

[font]
size = 12


[font.normal]
family = "MonaspiceNe Nerd Font Mono"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "~/.local/share/mise/shims/zellij"]

[window]
startup_mode = "Maximized"
option_as_alt = "Both"

[env]
TERM = "xterm-256color"
