import = ["~/.config/alacritty/rose-pine.toml"]

[font]
size = 12

[font.bold_italic]
family = "RecMonoLinear Nerd Font Mono"

[font.bold]
family = "RecMonoLinear Nerd Font Mono"

[font.italic]
family = "RecMonoLinear Nerd Font Mono"

[font.normal]
family = "RecMonoLinear Nerd Font Mono"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "~/.local/share/mise/shims/zellij"]

[window]
startup_mode = "Maximized"
option_as_alt = "Both"
