default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-case-conflict
      - id: check-toml
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-symlinks
      - id: fix-encoding-pragma
      - id: mixed-line-ending
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          [
            "--max-line-length=150",
            "--ignore=E203,E402,E501,E800,W503,W391,E261,D203,E731,F401",
            "--select=B,C,E,F,W,T4,B9",
          ]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=150]
  - repo: https://github.com/kdheepak/conventional-commits-precommit
    rev: v0.3.7
    hooks:
      - id: check-commit-msg
