default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-case-conflict
      - id: check-toml
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: check-symlinks
      - id: fix-encoding-pragma
      - id: mixed-line-ending
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=150]
  - repo: https://github.com/kdheepak/conventional-commits-precommit
    rev: v0.3.8
    hooks:
      - id: check-commit-msg
