repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: flake8
      - id: pretty-format-json
        args: [--autofix]
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
      - id: black
        args: [--line-length=88, --safe]
        python_version: python3.6

