[workspace]
authors = ["Dheepak Krishnamurthy <1813121+kdheepak@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "dotfiles"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[tasks.install-pipx-tools]
description = "Install all pipx tools using uv tool install"
cmd = """
uv tool install pylint && \
uv tool install toml-sort && \
uv tool install pre-commit && \
uv tool install black && \
uv tool install cookiecutter && \
uv tool install httpie && \
uv tool install ruff && \
uv tool install mypy && \
uv tool install isort && \
uv tool install commitizen && \
uv tool install json-schema-for-humans && \
uv tool install cmake-language-server && \
uv tool install git-copilot-commit && \
uv tool install python-semantic-release && \
uv tool install py7zr && \
uv tool install mkdocs --with mkdocs-material && \
uv tool install bump2version && \
uv tool install yamlfix && \
uv tool install codespell && \
uv tool install pptx2md && \
uv tool install weasyprint && \
uv tool install pyfiglet && \
uv tool install llm && \
uv tool install gitingest && \
uv tool install ddgr && \
uv tool install dunk && \
uv tool install harlequin && \
uv tool install git-revise
"""

[tasks.install-cargo-tools]
description = "Install all cargo tools using cargo binstall"
cmd = """
cargo install cargo-binstall && \
cargo binstall -y juliaup && \
cargo binstall -y uv-migrator && \
cargo binstall -y atuin && \
cargo binstall -y broot && \
cargo binstall -y yazi-fm && \
cargo binstall -y eza && \
cargo binstall -y lazyjj && \
cargo binstall -y ftdv && \
cargo binstall -y git-trim && \
cargo binstall -y git-cliff && \
cargo binstall -y gitui && \
cargo binstall -y gitu && \
cargo binstall -y onefetch && \
cargo binstall -y git-absorb && \
cargo binstall -y selene && \
cargo binstall -y xh && \
cargo binstall -y jless && \
cargo binstall -y bottom && \
cargo binstall -y hyperfine && \
cargo binstall -y cargo-criterion && \
cargo binstall -y license-generator && \
cargo binstall -y cargo-license && \
cargo binstall -y choose && \
cargo binstall -y ouch && \
cargo binstall -y pastel && \
cargo binstall -y procs && \
cargo binstall -y tealdeer && \
cargo binstall -y eva && \
cargo binstall -y bandwhich && \
cargo binstall -y bacon && \
cargo binstall -y cargo-deny && \
cargo binstall -y cargo-dist && \
cargo binstall -y cargo-edit && \
cargo binstall -y cargo-feature && \
cargo binstall -y cargo-generate && \
cargo binstall -y cargo-insta && \
cargo binstall -y cargo-nextest && \
cargo binstall -y mergiraf && \
cargo binstall -y cargo-shear && \
cargo binstall -y cross && \
cargo binstall -y flamegraph && \
cargo binstall -y wasm-tools && \
cargo binstall -y toml-cli && \
cargo binstall -y wasm-bindgen-cli && \
cargo binstall -y wasm-pack && \
cargo binstall -y cargo-zigbuild && \
cargo binstall -y numbat-cli && \
cargo binstall -y fd-find && \
cargo binstall -y miniserve && \
cargo binstall -y du-dust && \
cargo binstall -y kmeans_colors && \
cargo binstall -y xsv && \
cargo binstall -y lolcrab && \
cargo binstall -y navi && \
cargo binstall -y viu && \
cargo binstall -y monochora && \
cargo binstall -y auto-palette-cli && \
cargo binstall -y svgbob_cli && \
cargo binstall -y sqlx-cli
"""

[dependencies]
