version = 1

[envs.fzf]
channels = ["conda-forge"]
dependencies = { fzf = "*" }
exposed = { fzf = "fzf" }

[envs.gh]
channels = ["conda-forge"]
dependencies = { gh = "*" }
exposed = { gh = "gh" }

[envs.nvim]
channels = ["conda-forge"]
dependencies = { nvim = "*" }
exposed = { nvim = "nvim" }

[envs.btop]
channels = ["conda-forge"]
dependencies = { btop = "*" }
exposed = { btop = "btop" }

[envs.ripgrep]
channels = ["conda-forge"]
dependencies = { ripgrep = "*" }
exposed = { rg = "rg" }

[envs.starship]
channels = ["conda-forge"]
dependencies = { starship = "*" }
exposed = { starship = "starship" }

[envs.direnv]
channels = ["conda-forge"]
dependencies = { direnv = "*" }
exposed = { direnv = "direnv" }

[envs.zoxide]
channels = ["conda-forge"]
dependencies = { zoxide = "*" }
exposed = { zoxide = "zoxide" }

[envs.uv]
channels = ["conda-forge"]
dependencies = { uv = "*" }
exposed = { uv = "uv", uvx = "uvx" }

[envs.rust]
channels = ["conda-forge"]
dependencies = { rust = "*" }
exposed = { cargo = "cargo", cargo-clippy = "cargo-clippy", cargo-fmt = "cargo-fmt", clippy-driver = "clippy-driver", rust-analyzer = "rust-analyzer", rust-gdb = "rust-gdb", rust-gdbgui = "rust-gdbgui", rust-lldb = "rust-lldb", rustc = "rustc", rustdoc = "rustdoc", rustfmt = "rustfmt" }

[envs.zed]
channels = ["conda-forge"]
dependencies = { zed = "*" }
exposed = { zed = "zed" }
shortcuts = ["zed"]

[envs.zig]
channels = ["conda-forge"]
dependencies = { zig = "*" }
exposed = { zig = "zig" }

[envs.git]
channels = ["conda-forge"]
dependencies = { git = "*" }
exposed = { git = "git", git-credential-osxkeychain = "git-credential-osxkeychain", git-cvsserver = "git-cvsserver", git-receive-pack = "git-receive-pack", git-shell = "git-shell", git-upload-archive = "git-upload-archive", git-upload-pack = "git-upload-pack", gitk = "gitk", scalar = "scalar" }

[envs.bash]
channels = ["conda-forge"]
dependencies = { bash = "*" }
exposed = { bash = "bash", bashbug = "bashbug" }

[envs.bat]
channels = ["conda-forge"]
dependencies = { bat = "*" }
exposed = { bat = "bat" }

[envs.pandoc]
channels = ["conda-forge"]
dependencies = { pandoc = "*" }
exposed = { pandoc = "pandoc", pandoc-lua = "pandoc-lua", pandoc-server = "pandoc-server" }

[envs.asciinema]
channels = ["conda-forge"]
dependencies = { asciinema = "*" }
exposed = { asciinema = "asciinema" }

[envs.p7zip]
channels = ["conda-forge"]
dependencies = { p7zip = "*" }
exposed = { 7z = "7z", 7za = "7za", 7zr = "7zr" }

[envs.typst]
channels = ["conda-forge"]
dependencies = { typst = "*" }
exposed = { typst = "typst" }

[envs.eza]
channels = ["conda-forge"]
dependencies = { eza = "*" }
exposed = { eza = "eza" }

[envs.jq]
channels = ["conda-forge"]
dependencies = { jq = "*" }
exposed = { jq = "jq" }

[envs.helix]
channels = ["conda-forge"]
dependencies = { helix = "*" }
exposed = { hx = "hx" }

[envs.watchexec]
channels = ["conda-forge"]
dependencies = { watchexec = "*" }
exposed = { watchexec = "watchexec" }

[envs.go-gum]
channels = ["conda-forge"]
dependencies = { go-gum = "*" }
exposed = { gum = "gum" }

[envs.cosign]
channels = ["conda-forge"]
dependencies = { cosign = "*" }
exposed = { cosign = "cosign" }

[envs.lazygit]
channels = ["conda-forge"]
dependencies = { lazygit = "*" }
exposed = { lazygit = "lazygit" }

[envs.jujutsu]
channels = ["conda-forge"]
dependencies = { jujutsu = "*" }
exposed = { jj = "jj" }

[envs.difftastic]
channels = ["conda-forge"]
dependencies = { difftastic = "*" }
exposed = { difft = "difft" }

[envs.git-delta]
channels = ["conda-forge"]
dependencies = { git-delta = "*" }
exposed = { delta = "delta" }

[envs.shellcheck]
channels = ["conda-forge"]
dependencies = { shellcheck = "*" }
exposed = { shellcheck = "shellcheck" }

[envs.stylua]
channels = ["conda-forge"]
dependencies = { stylua = "*" }
exposed = { stylua = "stylua" }

[envs.lua-language-server]
channels = ["conda-forge"]
dependencies = { lua-language-server = "*" }
exposed = { lua-language-server = "lua-language-server" }

[envs.yamllint]
channels = ["conda-forge"]
dependencies = { yamllint = "*" }
exposed = { yamllint = "yamllint" }

[envs.tokei]
channels = ["conda-forge"]
dependencies = { tokei = "*" }
exposed = { tokei = "tokei" }

[envs.typstyle]
channels = ["conda-forge"]
dependencies = { typstyle = "*" }
exposed = { typstyle = "typstyle" }

[envs.actionlint]
channels = ["conda-forge"]
dependencies = { actionlint = "*" }
exposed = { actionlint = "actionlint" }

[envs.lychee]
channels = ["conda-forge"]
dependencies = { lychee = "*" }
exposed = { lychee = "lychee" }

[envs.glow-md]
channels = ["conda-forge"]
dependencies = { glow-md = "*" }
exposed = { glow = "glow" }

[envs.hexyl]
channels = ["conda-forge"]
dependencies = { hexyl = "*" }
exposed = { hexyl = "hexyl" }

[envs.curlie]
channels = ["conda-forge"]
dependencies = { curlie = "*" }
exposed = { curlie = "curlie" }

[envs.just]
channels = ["conda-forge"]
dependencies = { just = "*" }
exposed = { just = "just" }

[envs.duckdb]
channels = ["conda-forge"]
dependencies = { duckdb = "*" }

[envs.python-duckdb]
channels = ["conda-forge"]
dependencies = { python-duckdb = "*" }

[envs.duckdb-cli]
channels = ["conda-forge"]
dependencies = { duckdb-cli = "*" }
exposed = { duckdb = "duckdb" }

[envs.duckdb-extension-json]
channels = ["conda-forge"]
dependencies = { duckdb-extension-json = "*" }

[envs.duckdb-extension-autocomplete]
channels = ["conda-forge"]
dependencies = { duckdb-extension-autocomplete = "*" }

[envs.sqlite]
channels = ["conda-forge"]
dependencies = { sqlite = "*" }
exposed = { sqlite3 = "sqlite3" }

[envs.tree-sitter-cli]
channels = ["conda-forge"]
dependencies = { tree-sitter-cli = "*" }
exposed = { tree-sitter = "tree-sitter" }

[envs.taplo]
channels = ["conda-forge"]
dependencies = { taplo = "*" }
exposed = { taplo = "taplo" }

[envs.ninja]
channels = ["conda-forge"]
dependencies = { ninja = "*" }
exposed = { ninja = "ninja" }

[envs.cmake]
channels = ["conda-forge"]
dependencies = { cmake = "*" }
exposed = { ccmake = "ccmake", cmake = "cmake", cpack = "cpack", ctest = "ctest" }

[envs.marksman]
channels = ["conda-forge"]
dependencies = { marksman = "*" }
exposed = { marksman = "marksman" }

[envs.coreutils]
channels = ["conda-forge"]
dependencies = { coreutils = "*" }
exposed = { "[" = "[", b2sum = "b2sum", base32 = "base32", base64 = "base64", basename = "basename", basenc = "basenc", cat = "cat", chcon = "chcon", chgrp = "chgrp", chmod = "chmod", chown = "chown", chroot = "chroot", cksum = "cksum", comm = "comm", cp = "cp", csplit = "csplit", cut = "cut", date = "date", dd = "dd", dir = "dir", dircolors = "dircolors", dirname = "dirname", du = "du", echo = "echo", env = "env", expand = "expand", expr = "expr", factor = "factor", false = "false", fmt = "fmt", fold = "fold", groups = "groups", head = "head", hostid = "hostid", id = "id", install = "install", join = "join", kill = "kill", link = "link", ln = "ln", logname = "logname", ls = "ls", md5sum = "md5sum", mkdir = "mkdir", mkfifo = "mkfifo", mknod = "mknod", mktemp = "mktemp", mv = "mv", nice = "nice", nl = "nl", nohup = "nohup", nproc = "nproc", numfmt = "numfmt", od = "od", paste = "paste", pathchk = "pathchk", pinky = "pinky", pr = "pr", printenv = "printenv", printf = "printf", ptx = "ptx", pwd = "pwd", readlink = "readlink", realpath = "realpath", rm = "rm", rmdir = "rmdir", runcon = "runcon", seq = "seq", sha1sum = "sha1sum", sha224sum = "sha224sum", sha256sum = "sha256sum", sha384sum = "sha384sum", sha512sum = "sha512sum", shred = "shred", shuf = "shuf", sleep = "sleep", sort = "sort", split = "split", stat = "stat", stty = "stty", sum = "sum", sync = "sync", tac = "tac", tail = "tail", tee = "tee", test = "test", timeout = "timeout", touch = "touch", tr = "tr", true = "true", truncate = "truncate", tsort = "tsort", tty = "tty", uname = "uname", unexpand = "unexpand", uniq = "uniq", unlink = "unlink", uptime = "uptime", users = "users", vdir = "vdir", wc = "wc", who = "who", whoami = "whoami", yes = "yes" }

[envs.hurl]
channels = ["conda-forge"]
dependencies = { hurl = "*" }
exposed = { hurl = "hurl", hurlfmt = "hurlfmt" }

[envs.age]
channels = ["conda-forge"]
dependencies = { age = "*" }
exposed = { age = "age", age-keygen = "age-keygen" }

[envs.packer]
channels = ["conda-forge"]
dependencies = { packer = "*" }
exposed = { packer = "packer" }

[envs.go-sops]
channels = ["conda-forge"]
dependencies = { go-sops = "*" }
exposed = { sops = "sops" }

[envs.superfile]
channels = ["conda-forge"]
dependencies = { superfile = "*" }
exposed = { spf = "spf" }

[envs.television]
channels = ["conda-forge"]
dependencies = { television = "*" }
exposed = { tv = "tv" }

[envs.r-tinytex]
channels = ["conda-forge"]
dependencies = { r-tinytex = "*" }

[envs.vhs]
channels = ["conda-forge"]
dependencies = { vhs = "*" }
exposed = { vhs = "vhs" }

[envs.mods]
channels = ["conda-forge"]
dependencies = { mods = "*" }
exposed = { mods = "mods" }

[envs.traefik]
channels = ["conda-forge"]
dependencies = { traefik = "*" }
exposed = { traefik = "traefik" }

[envs.tectonic]
channels = ["conda-forge"]
dependencies = { tectonic = "*" }
exposed = { tectonic = "tectonic" }

[envs.nodejs]
channels = ["conda-forge"]
dependencies = { nodejs = "*" }
exposed = { corepack = "corepack", node = "node", npm = "npm", npx = "npx" }

[envs.openssl]
channels = ["conda-forge"]
dependencies = { openssl = "*" }
exposed = { c_rehash = "c_rehash", openssl = "openssl" }

[envs.pkg-config]
channels = ["conda-forge"]
dependencies = { pkg-config = "*" }
exposed = { "aarch64-apple-darwin20.0.0-pkg-config" = "aarch64-apple-darwin20.0.0-pkg-config", "arm64-apple-darwin20.0.0-pkg-config" = "arm64-apple-darwin20.0.0-pkg-config", pkg-config = "pkg-config", "pkg-config.bin" = "pkg-config.bin" }

[envs.compilers]
channels = ["conda-forge"]
dependencies = { compilers = "*" }

[envs.ffmpeg]
channels = ["conda-forge"]
dependencies = { ffmpeg = "*" }
exposed = { ffmpeg = "ffmpeg", ffplay = "ffplay", ffprobe = "ffprobe" }

[envs.imagemagick]
channels = ["conda-forge"]
dependencies = { imagemagick = "*" }
exposed = { "Magick++-config" = "Magick++-config", MagickCore-config = "MagickCore-config", MagickWand-config = "MagickWand-config", animate = "animate", compare = "compare", composite = "composite", conjure = "conjure", convert = "convert", display = "display", identify = "identify", import = "import", magick = "magick", magick-script = "magick-script", mogrify = "mogrify", montage = "montage", stream = "stream" }

[envs.rattler-build]
channels = ["conda-forge"]
dependencies = { rattler-build = "*" }
exposed = { rattler-build = "rattler-build" }

[envs.pixi-pack]
channels = ["conda-forge"]
dependencies = { pixi-pack = "*" }
exposed = { pixi-pack = "pixi-pack" }

[envs.data-science]
channels = ["conda-forge"]
dependencies = { jupyter = "*", numpy = "*", pandas = "*", matplotlib = "*", ipython = "*" }
exposed = { jupyter = "jupyter", ipython = "ipython" }

[envs.bun-baseline]
channels = ["https://prefix.dev/brads-forge"]
platform = "osx-64"
dependencies = { bun-baseline = "*" }
exposed = { bun = "bun" }
