# [env]
# _.python.venv = { path = ".venv", create = true }

[settings]
experimental = true
pipx_uvx = true
python.uv_venv_auto = true

[tools]
rust = "latest"
go = "latest"
neovim = "stable"
direnv = "latest"
fzf = "latest"
bat = "latest"              # Better cat with syntax highlighting
ripgrep = "latest"          # Better grep (rg command)
fd = "latest"               # Better find
sd = "latest"               # Better sed
tmux = "latest"
jq = "latest"
dust = "latest"             # Better du
uv = "latest"
jujutsu = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
tree-sitter = "latest"
nim = "latest"

github-cli = "latest"
lazygit = "latest"
difftastic = "latest"
delta = "latest"            # Better git diffs (complements difftastic)
"cargo:git-trim" = "latest"

"cargo:cargo-binstall" = "latest"
"cargo:zellij" = "latest"
"cargo:pastel" = "latest"
"cargo:eza" = "latest"
"cargo:license-generator" = "latest"
"cargo:rust-script" = "latest"
"cargo:scriptisto" = "latest"
"cargo:typstyle" = "latest"
"cargo:serie" = "latest"
"cargo:yazi-fm" = "latest"
"cargo:tokei" = "latest"    # Code statistics
"cargo:hyperfine" = "latest" # Benchmarking tool
"cargo:just" = "latest"     # Command runner (Makefile alternative)
"cargo:bottom" = "latest"   # Better top/htop
"cargo:procs" = "latest"    # Better ps
"cargo:tealdeer" = "latest"
"cargo:gitui" = "latest"
"cargo:dua-cli" = "latest"
"cargo:hexyl" = "latest"
"cargo:fx" = "latest" # Interactive JSON tool
"cargo:jless" = "latest"    # JSON viewer
"cargo:zoxide" = "latest"   # Smart cd (z command)
"cargo:xh" = "latest"       # Better curl/httpie
"cargo:ouch" = "latest"

