# [env]
# _.python.venv = { path = ".venv", create = true }  # Would create Python virtual environment in .venv directory

[settings]
experimental = true # Enable experimental features in mise
pipx_uvx = true # Enable pipx and uvx integration for Python package management
pipx.uvx = true # Enable pipx and uvx integration for Python package management
python.uv_venv_auto = true # Automatically create Python virtual environments using uv
python.compile = false # always download precompiled binaries
idiomatic_version_file_enable_tools = [
  "python",
] # Enable version file detection for Python projects
disable_backends = ["asdf"] # Disable asdf backend (using mise instead)
status.show_env = true

[tools]
git = "latest"

# --- Languages and Runtimes ---
rust = "latest"   # Rust programming language compiler and toolchain
go = "latest"     # Go programming language compiler
python = "latest" # Python programming language interpreter
bun = "latest"    # Fast JavaScript runtime and package manager

# --- Python Ecosystem Tools (via pipx) ---
"pipx:pylint" = "latest"       # Linter
"pipx:toml-sort" = "latest"    # TOML file sorter
"pipx:pre-commit" = "latest"   # Git pre-commit hook framework
"pipx:black" = "latest"        # Python code formatter
"pipx:cookiecutter" = "latest" # Project template tool
"pipx:httpie" = "latest"       # HTTP client for APIs
"pipx:llm" = "latest"          # Large Language Model CLI tool
"pipx:ruff" = "latest"         # Fast Python linter and formatter
"pipx:pptx2md" = "latest"      # Convert powerpoint to markdown
"pipx:bump2version" = "latest" # Bump version
"pipx:ty" = "latest"           # type checker
uv = "latest"                  # Fast Python package installer and resolver
"cargo:uv-migrator" = "latest" # Move from setup.py, conda env etc to uv

# --- Node.js Ecosystem Tools (via npm) ---
"npm:markdownlint-cli" = "latest" # Markdown linting tool
"npm:prettier" = "latest"         # Code formatter

# --- Editors ---
neovim = "latest" # Modern Vim-based text editor
helix = "latest"

# --- Shell and Productivity ---
direnv = "latest"        # Environment variable management per directory
fzf = "latest"           # Fuzzy finder for command line
usage = "latest"         # Tool for generating CLI usage documentation
watchexec = "latest"     # File watcher that executes commands on changes
zoxide = "latest"        # Smart cd command (z command)
gum = "latest"           # Tool for glamorous shell scripts and TUI components
starship = "latest"      # Cross-shell prompt customization
zellij = "latest"        # Terminal workspace manager (tmux alternative)
"cargo:atuin" = "latest" # Replaces shell history with a powerful, searchable database
cosign = "latest"        # A tool for Container Signing, Verification and Storage
pandoc = "latest"        # Convert markdown to word, pdf etc

# --- File System and Navigation ---
bat = "latest"             # Better cat with syntax highlighting
ripgrep = "latest"         # Better grep (rg command)
fd = "latest"              # Better find
sd = "latest"              # Better sed
dust = "latest"            # Better du - disk usage analyzer
"cargo:broot" = "latest"   # Tree-view file manager - cargo:broot
"cargo:yazi-fm" = "latest" # Terminal file manager - cargo:yazi-fm
"cargo:eza" = "latest"     # Better ls command (formerly exa) - cargo:eza
dua = "latest"             # A tool to learn about disk usage, fast!
duf = "latest"             # A disk utility

# --- Git and Version Control ---
github-cli = "latest"              # GitHub command line interface
lazygit = "latest"                 # Terminal UI for Git commands
jujutsu = "latest"                 # Git-compatible VCS with advanced features
difftastic = "latest"              # Structural diff tool for code
delta = "latest"                   # Better git diffs (complements difftastic)
"cargo:git-trim" = "latest"        # Git branch cleanup tool
"cargo:git-cliff" = "latest"       # Changelog generator from git history
"cargo:gitui" = "latest"           # Terminal UI for Git
"cargo:onefetch" = "latest"        # Git repository information display
"cargo:serie" = "latest"           # Rich git repository analytics
"aqua:github/git-sizer" = "latest" # Summary about git repo size
"aqua:git-lfs/git-lfs" = "latest"

# --- Linters, Formatters, and Code Quality ---
shellcheck = "latest"          # Shell script static analysis tool
shfmt = "latest"               # Shell script formatter
stylua = "latest"              # Lua code formatter (version 2)
lua-language-server = "latest" # Lua language server for IDE features (version 2)
yamllint = "latest"            # YAML linting tool (version 1.35)
typos = "latest"               # Source code spell checker
tokei = "latest"               # Code statistics and line counting - cargo:tokei
typstyle = "latest"            # Typst markup language formatter - cargo:typstyle

# --- Data Processing and Viewing ---
jq = "latest"            # JSON processor and query tool
yq = "latest"            # YAML processor (like jq for YAML)
glow = "latest"          # Markdown renderer for terminal
hexyl = "latest"         # Command-line hex viewer
jless = "latest"         # JSON viewer for terminal - cargo:jless
"aqua:curlie" = "latest" # curl-like HTTP client (via Aqua)
"aqua:fx" = "latest"     # Interactive JSON tool (via Aqua)
"cargo:xh" = "latest"    # Better curl/httpie HTTP client (via cargo)

# --- Utilities ---
"just" = "latest"                    # Command runner (Makefile alternative)
"cargo:cargo-binstall" = "latest"    # Binary installation for cargo packages
"cargo:bottom" = "latest"            # Better top/htop system monitor
"cargo:hyperfine" = "latest"         # Command-line benchmarking tool
"cargo:license-generator" = "latest" # Software license generator
"cargo:ouch" = "latest"              # Archive extraction tool
"cargo:pastel" = "latest"            # Color manipulation and palette tool
"cargo:procs" = "latest"             # Better ps process viewer
"cargo:rust-script" = "latest"       # Run Rust files as scripts
"cargo:scriptisto" = "latest"        # Language-agnostic script runner
"cargo:tealdeer" = "latest"          # Fast tldr pages implementation
tree-sitter = "latest"               # Parsing library for syntax highlighting
"cargo:eva" = "latest"               # CLI expressions and math (like bc on steroids)
"cargo:bandwhich" = "latest"         # Network traffic analyzer
"cargo:bacon" = "latest"
"cargo:cargo-deny" = "latest"
"cargo:cargo-dist" = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-feature" = "latest"
"cargo:cargo-generate" = "latest"
"cargo:cargo-insta" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-shear" = "latest"
"cargo:cargo-show" = "latest"
"cargo:cross" = "latest"
"cargo:flamegraph" = "latest"
"cargo:wasm-tools" = "latest"
"cargo:toml-cli" = "latest"
taplo = "latest"                     # TOML validator
ninja = "latest"
cmake = "3.29"
coreutils = "latest"

# --- AI ---
"aqua:charmbracelet/mods" = "latest"

# --- Containerization ---
podman = "latest"
lazydocker = "latest"

# --- Database Management ---
"cargo:sqlx-cli" = "latest"
"pipx:harlequin" = "latest"

[tasks]
uv = "uv sync --group dev --all-extras"
clean = ["rm -rf .venv", "rm -rf node_modules"]
lint = "pre-commit run --all-files"
setup-python = "uv pip install --system ipython jupyter neovim python-localvenv-kernel jupyter jupyterlab jupyterlab_execute_time jupyterlab-lsp python-lsp-server jupytext panel hvplot holoviews matplotlib numpy pandas 'ibis-framework[duckdb,geospatial]' lonboard jupyter_copilot jupyterlab-quarto jupyterlab-rainbow-brackets jupyterlab-code-formatter"

[tasks.changelog]
description = "Generate a changelog for the current version"
outputs = ["CHANGELOG.md"]
run = ["git-cliff --config .cliff.toml --output CHANGELOG.md"]
