[settings]
experimental = true

[tools]
"cargo:cargo-binstall" = "latest"
"cargo:zellij" = "latest"
neovim = "nightly"
"cargo:yazi-cli" = "latest"
"cargo:git-trim" = "latest"
"cargo:pastel" = "latest"
"cargo:eza" = "latest"
github-cli = "latest"
lazygit = "latest"
"cargo:rust-script" = "latest"
"cargo:scriptisto" = "latest"
tig = "latest"
go = "latest"
node = "latest"
difftastic = "latest"
"cargo:typstyle" = "latest"
"cargo:serie" = "latest"
tmux = "latest"
"cargo:yazi-fm" = "latest"
