[settings]
experimental = true

[tools]
"cargo:cargo-binstall" = "latest"
"cargo:zellij" = "latest"
neovim = "latest"
"cargo:yazi-cli" = "latest"
starship = "latest"
delta = "latest"
ripgrep = "latest"
bat = "latest"
fzf = "latest"
"cargo:git-trim" = "latest"
"cargo:pastel" = "latest"
direnv = "latest"
"cargo:exa" = "latest"
github-cli = "latest"
"pipx:pylint" = "latest"
lazygit = "latest"
"cargo:rust-script" = "latest"
"cargo:scriptisto" = "latest"
tig = "latest"
pandoc = "latest"
jq = "latest"
just = "latest"
tokei = "latest"
go = "latest"
tmux = "latest"
"pipx:black" = "latest"
node = "latest"
difftastic = "latest"
