# [env]
# _.python.venv = { path = ".venv", create = true }  # Commented out: Would create Python virtual environment in .venv directory

[settings]
experimental = true                                 # Enable experimental features in mise
pipx_uvx = true                                     # Enable pipx and uvx integration for Python package management
python.uv_venv_auto = true                          # Automatically create Python virtual environments using uv
python.compile = false                              # Disable Python bytecode compilation for faster startup
idiomatic_version_file_enable_tools = ["python"]    # Enable version file detection for Python projects
disable_backends = ["asdf"]                         # Disable asdf backend (using mise instead)

[tools]
rust = "latest"                                     # Rust programming language compiler and toolchain
go = "latest"                                       # Go programming language compiler
neovim = "stable"                                   # Modern Vim-based text editor
direnv = "latest"                                   # Environment variable management per directory
fzf = "latest"                                      # Fuzzy finder for command line
bat = "latest"                                      # Better cat with syntax highlighting
ripgrep = "latest"                                  # Better grep (rg command)
fd = "latest"                                       # Better find
sd = "latest"                                       # Better sed
tmux = "latest"                                     # Terminal multiplexer for session management
jq = "latest"                                       # JSON processor and query tool
yq = "latest"                                       # YAML processor (like jq for YAML)
dust = "latest"                                     # Better du - disk usage analyzer
uv = "latest"                                       # Fast Python package installer and resolver
jujutsu = "latest"                                  # Git-compatible VCS with advanced features
shellcheck = "latest"                               # Shell script static analysis tool
shfmt = "latest"                                    # Shell script formatter
starship = "latest"                                 # Cross-shell prompt customization
tree-sitter = "latest"                              # Parsing library for syntax highlighting
nim = "latest"                                      # Nim programming language compiler
zellij = "latest"                                   # Terminal workspace manager (tmux alternative)
glow = "latest"                                     # Markdown renderer for terminal
hexyl = "latest"                                    # Command-line hex viewer
usage = "latest"                                    # Tool for generating CLI usage documentation
watchexec = "latest"                                # File watcher that executes commands on changes
python = "latest"                                   # Python programming language interpreter
gum = "latest"                                      # Tool for glamorous shell scripts and TUI components

stylua = "2"                                        # Lua code formatter (version 2)
lua-language-server = "2"                           # Lua language server for IDE features (version 2)
bun = "latest"                                      # Fast JavaScript runtime and package manager
"npm:markdownlint-cli" = "latest"                   # Markdown linting tool
"npm:prettier" = "3"                                # Code formatter
yamllint = "1.35"                                   # YAML linting tool (version 1.35)
typos = "latest"                                    # Source code spell checker

"aqua:curlie" = "latest"                            # curl-like HTTP client
"aqua:fx" = "latest"                                # Interactive JSON tool

"pipx:toml-sort" = "latest"                         # TOML file sorter
"pipx:pre-commit" = "latest"                        # Git pre-commit hook framework
"pipx:black" = "latest"                             # Python code formatter
"pipx:cookiecutter" = "latest"                      # Project template tool
"pipx:httpie" = "latest"                            # HTTP client for APIs
"pipx:llm" = "latest"                               # Large Language Model CLI tool
"pipx:ruff" = "latest"                              # Fast Python linter and formatter

github-cli = "latest"                               # GitHub command line interface
lazygit = "latest"                                  # Terminal UI for Git commands
difftastic = "latest"                               # Structural diff tool for code
delta = "latest"                                    # Better git diffs (complements difftastic)

"cargo:git-trim" = "latest"                         # Git branch cleanup tool
"cargo:cargo-binstall" = "latest"                   # Binary installation for cargo packages
"cargo:bottom" = "latest"                           # Better top/htop system monitor
"cargo:broot" = "latest"                            # Tree-view file manager
"cargo:dua-cli" = "latest"                          # Disk usage analyzer
"cargo:eza" = "latest"                              # Better ls command
"cargo:git-cliff" = "latest"                        # Changelog generator from git history
"cargo:gitui" = "latest"                            # Terminal UI for Git
"cargo:hyperfine" = "latest"                        # Command-line benchmarking tool
"cargo:jless" = "latest"                            # JSON viewer for terminal
"cargo:just" = "latest"                             # Command runner (Makefile alternative)
"cargo:license-generator" = "latest"                # Software license generator
"cargo:onefetch" = "latest"                         # Git repository information display
"cargo:ouch" = "latest"                             # Archive extraction tool
"cargo:pastel" = "latest"                           # Color manipulation and palette tool
"cargo:procs" = "latest"                            # Better ps process viewer
"cargo:rust-script" = "latest"                      # Run Rust files as scripts
"cargo:scriptisto" = "latest"                       # Language-agnostic script runner
"cargo:serie" = "latest"                            # Rich git repository analytics
"cargo:tealdeer" = "latest"                         # Fast tldr pages implementation
"cargo:tokei" = "latest"                            # Code statistics and line counting
"cargo:typstyle" = "latest"                         # Typst markup language formatter
"cargo:xh" = "latest"                               # Better curl/httpie HTTP client
"cargo:yazi-fm" = "latest"                          # Terminal file manager
"cargo:zoxide" = "latest"                           # Smart cd command (z command)
