[settings]
experimental = true

[tools]
"cargo:cargo-binstall" = "latest"
"cargo:zellij" = "latest"
neovim = "nightly"
"cargo:yazi-cli" = "latest"
delta = "latest"
ripgrep = "latest"
bat = "latest"
"cargo:git-trim" = "latest"
"cargo:pastel" = "latest"
direnv = "latest"
"cargo:eza" = "latest"
github-cli = "latest"
lazygit = "latest"
"cargo:rust-script" = "latest"
"cargo:scriptisto" = "latest"
tig = "latest"
pandoc = "latest"
jq = "latest"
just = "latest"
tokei = "latest"
go = "latest"
node = "latest"
difftastic = "latest"
"cargo:typstyle" = "latest"
"cargo:serie" = "latest"
"cargo:starship" = "latest"
"ubi:junegunn/fzf" = "latest"
