#!/usr/bin/env bash
#MISE description="Initialize git repository if not already setup"

source ~/gitrepos/dotfiles/mise/tasks/utils

if [ -d .git ]; then
    info "Git repository already initialized"
else
    info "Initializing new Git repository..."
    git init . -b main
    success "Git repository initialized on main branch"
    info "Adding initial files..."
    git add .
    git commit -m "new: Initial commit"
    success "Created initial commit"
fi
