import = ["~/.config/alacritty/rose-pine.toml"]

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular"}
size = 12

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij attach --index 0 --create"]
